version: '3.2'

services:
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yaml

volumes:
  prometheus-data:
